### ISSUE TITLE
Error in Chapter-RegEx of aftv sites

### ISSUE THREAD

**Issue by drunsinn** [jklmli/mangopi#3]
Hello and thanks for your code!

I found and fixed two simple issues with the CHAPTER_FROM_SOURCE_REGEX for MangaFox and MangaHere. The error concern the generation of the url for each page.In the case of MangaFox it will only load the first page (and image) of each chapter. The problem with MangaHere dosen't really make a difference since the Server seems to correct the url.

Here are the fixed parts of the RegEx:
MangaFox:
'a href="(?P<url>[^"]_)**/1.html**"
MangaHere:
'0077" href="(?P<url>[^"]_)**/**"

I hope this helps :-)

**Comment by jklmli** [comment]
Hi - thanks for the feedback!  Mind creating a pull request for this?  I'd happily merge it in :)
